MSVC: fix weird clash in system header files on Win32/64 due to redef in system cstddef header file: Windows Kits\10\Include\10.0.22621.0\shared\rpcndr.h(203,9): error C2872: 'byte': ambiguous symbol