fix MSVC compiler error due to fz_assert checks failing: the given assertion(s) are not exeactly boolean expressions. This stringent check was added by us in the fz_assert support header to ensure assertion statements are strictly correct as subtle bugs have occurred in the past due to assertion statements being lax in type and only 'by default' evaluating to BOOLEAN results. Example: libeigen\unsupported\Eigen\src\MatrixFunctions\MatrixPower.h(541,3): error C2280: 'bool fz_assert_impl::validateBool4Assert(double)': attempting to reference a deleted function